// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SESMAN.Infrastructure;

#nullable disable

namespace SESMAN.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717074501_SavedRequestTableFix")]
    partial class SavedRequestTableFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SESMAN.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestLogId");

                    b.ToTable("RequestHeaders");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestLogId");

                    b.ToTable("RequestParameters");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.ResponseHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponseLogId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponseLogId");

                    b.ToTable("ResponseHeaders");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.ResponseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RequestLogId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequestLogId")
                        .IsUnique();

                    b.ToTable("ResponseLogs");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("SavedRequests");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequestHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SavedRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SavedRequestId");

                    b.ToTable("SavedRequestHeaders");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequestParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SavedRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SavedRequestId");

                    b.ToTable("SavedRequestParameters");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestHeader", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.RequestLog", null)
                        .WithMany("RequestHeaders")
                        .HasForeignKey("RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestParameter", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.RequestLog", null)
                        .WithMany("RequestParameters")
                        .HasForeignKey("RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.ResponseHeader", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.ResponseLog", null)
                        .WithMany("ResponseHeaders")
                        .HasForeignKey("ResponseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.ResponseLog", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.RequestLog", "RequestLog")
                        .WithOne("Response")
                        .HasForeignKey("SESMAN.Domain.Entities.ResponseLog", "RequestLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestLog");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequest", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.Collection", null)
                        .WithMany("SavedRequests")
                        .HasForeignKey("CollectionId");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequestHeader", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.SavedRequest", null)
                        .WithMany("SavedRequestHeaders")
                        .HasForeignKey("SavedRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequestParameter", b =>
                {
                    b.HasOne("SESMAN.Domain.Entities.SavedRequest", null)
                        .WithMany("SavedRequestParameters")
                        .HasForeignKey("SavedRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.Collection", b =>
                {
                    b.Navigation("SavedRequests");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.RequestLog", b =>
                {
                    b.Navigation("RequestHeaders");

                    b.Navigation("RequestParameters");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.ResponseLog", b =>
                {
                    b.Navigation("ResponseHeaders");
                });

            modelBuilder.Entity("SESMAN.Domain.Entities.SavedRequest", b =>
                {
                    b.Navigation("SavedRequestHeaders");

                    b.Navigation("SavedRequestParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
